config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  ##### Sign Up and Sign In and Sign Out
  get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  # get '/users/:id' => 'users#show', as: :user

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  
  get "/signout" => 'sessions#destroy'
    
  resources :posts
  resources :comments
  resources :categories
  resources :mappings
  resources :users do
    member do
      get '/following' => 'users#following'
      get '/followers' => 'users#followers'
      get '/posts' => 'posts#index'
      get '/posts/friends' => 'posts#index'
    end
  end
  resources :relations
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :mappings, :dependent => :destroy
	has_many :posts, :through=> :mappings

	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :user
	
	validates :user_id, :presence => true
	validates :body, :presence => true, :allow_nil => false
	
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
	
	belongs_to :post
	belongs_to :category
	
	validates :category_id, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	has_many :mappings
	has_many :categories, :through => :mappings

	belongs_to :user
	
	validates :title, :presence => true, :allow_nil => false
	validates :user_id, :presence => true, :allow_nil => false
	
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :active_relations, :class_name => "Relation",
                              :foreign_key=> "follower_id",
                              :dependent => :destroy
  has_many :passive_relations, :class_name => "Relation",
           :foreign_key=> "followed_id",
           :dependent => :destroy

  has_many :followings, :through  => :active_relations, :source => :followed
  has_many :followers, :through  => :passive_relations, :source => :follower

  has_secure_password
  
  validates :email, :uniqueness => true, :allow_nil => false
  validates :user_name, :uniqueness => true, :allow_nil => false
  validates :password, :presence => true, :allow_nil => false

  # Follows a user.
  def follow(other_user)
    active_relations.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relations.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user
  def following?(other_user)
    followings.include?(other_user)
  end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
    c = Comment.new
    c.user_id = params["user_id"]
    c.post_id = params["post_id"]
    c.date = Time.now
    c.body = params["body"]
    c.save
    redirect_to "/posts/#{c.post_id}"   
end

end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController

def create
	array = params["category_ids"]

	if array.nil?
		redirect_to "/posts/#{params["post_id"]}"
	else
		array.each{|category_id|
		m = Mapping.new
			m.category_id = category_id
			m.post_id = params["post_id"]
			m.save
		}
		redirect_to "/posts/#{params["post_id"]}"
	end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 before_action :find_post, :only => [:show, :edit, :update, :destroy]
 before_action :require_user, :only => [:new, :edit, :update, :edit, :destroy]

 def find_post
 	@post = Post.find_by(id: params[:id])
 end

 def index
   # search bar
   if params["keyword"].present?
     @posts = Post.where("body LIKE ? or title LIKE ?", "%#{params[:keyword]}%","%#{params[:keyword]}%")
                  .limit(1000).order('date desc').page(params[:page]).per(5)

   else
     if params[:id].present?
       @user = User.find_by(id: session[:user_id])
       @url_path = request.original_url.to_s;

       # show friends' posts
       if @url_path.include?"friends"
         @page_id = "friends_posts"
         @users = @user.followings
         @posts = Post.where(:user_id => @users.pluck("id")).order('date desc').page(params[:page]).per(5)
       else
       # only show the signed in user's posts
         @page_id = "posts"
         @posts = @user.posts.order('date desc').page(params[:page]).per(5)
       end
       # home page shows all users' posts
     else
       @posts = Post.all.limit(1000).order('date desc').page(params[:page]).per(5)
     end
   end
 end

 def show
 	session["post_id"] = @post.id
 	@user_id = session["user_id"] 
	if @post == nil
		redirect to posts_url
    end
 end

 def require_user
	if session[:user_id].blank?
 		redirect_to root_url, notice: "You need to sign in first"
 	end
 end
	
 def new	
 	@post = Post.new
 	@user_id = session["user_id"]
 end

 def create
 	@post = Post.new
	@post.user_id = session["user_id"]
	@post.title = params[:title]
	@post.date = Time.now
	@post.body = params[:body]
	
	if @post.save
		redirect_to post_url(@post.id)
	else 
		render 'new'
  end

 end
 			
 def edit
 end

 def update

	@post.user_id = session["user_id"]
	@post.title = params[:title]
	@post.date = params[:date]
	@post.body = params[:body]
	@post.save
	
	redirect_to post_url(@post.id)
 end

 def destroy
    @post.delete
    redirect_to posts_url
 end

 def get_friends
   @page_id = "friends_posts"
   @user = User.find_by(id: params[:id])
   @users = @user.followings
   @posts = Post.where(:user_id => @users.pluck("id")).order('date desc').page(params[:page]).per(5)
   render posts_url

 end
 
end
	
	

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :current_user, :only => [:create, :destroy]

  def current_user
    @current_user = User.find_by(:id => session["user_id"])
  end

  def create
    @user = User.find(params[:followed_id])
    @current_user.follow(@user)
    redirect_to user_url(@user.id)
  end

  def destroy
    @user = Relation.find(params[:id]).followed
    @current_user.unfollow(@user)
    redirect_to user_url(@user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      if user.authenticate(params[:password])
        session["user_id"] = user.id
        redirect_to root_url, notice: "Welcome back!"
      else
        redirect_to root_url, notice: "Unknown email or password."
      end
    else
      redirect_to root_url, notice: "Unknown email or password."
    end
  end
  
  def destroy
  	session.delete("user_id")
  		redirect_to root_url, notice: "You have signed out."
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show]
  before_action :find_user, except: [:create, :authorize]

  def find_user
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_name: params[:name], email: params[:email], password: params[:password])
    if @user.save
      redirect_to root_url, notice: "Thanks for signing up."
    else
      render "new"
    end

  end
  
  def authorize

   if session[:user_id].blank? 
   		redirect_to root_url, notice: "Nice try!"
   end

  end
  
  def show
    @page_id = "profile"
  end

  def following

    @title = "Following"
    @users = @user.followings
    render 'relations/show.html'

  end

  def followers

    @title = "Followers"
    @users = @user.followers
    render 'relations/show.html'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<%= tinymce_assets %>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <%= form_tag "/posts/#{@post.id}", :method => 'patch' do %>
      <p>
        <label>Title:</label> <input value="<%= @post.title %>" name="title" size="30">
         <input type="hidden" value="<%= Time.now %>" name="date">
      </p>

        <%= text_area_tag :body, simple_format(@post.body), :class => "tinymce", :rows => 60, :cols => 80 %>
        <%= tinymce %>

      <button style="margin-top:10px; background-color:#218C8D" class="btn btn-small">Submit</button>
    <% end %>
  </div>
  <div class="col-mid-1"></div>
</div>

app/views/posts/index.html.erb
<div class="well">
  <div class="row">
    <div class="col-md-7">
      <% if session["user_id"].present? %>
          <p>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            <span class="glyphicon-class"><%= link_to "Write Something New", new_post_url, :class=>"blackColor" %></span>
          <p>
      <% else %>
          <p>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <span class="glyphicon-class"><%= link_to "Sign Up", '/signup'%> or <%= link_to "Sign In", '/login'%> to Start Writing</span>
          <p>
      <% end %>
    </div>
    <div class="col-md-5"></div>
  </div>

  <%= paginate @posts %>
  
  <% @posts.each do |post| %>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-7">
			<div class="panel panel-default">
				<div class="panel-heading">

					<h3 style="font-family:verdana; font-weight:700" class="panel-title">
						<span class="glyphicons glyphicons-cat"></span>
						<%= link_to post.title, post_url(post.id),  :method => 'get'%>
						<h6><%= link_to User.where(:id=>post.user_id).pluck("user_name")[0], user_url(post.user_id),
                                        :class=>"blackColor" %></h6>
						<h6 style="color:darkgray;font-family:verdana" ><%= post.date %></h6>
                    </h3>

					<% if session["user_id"].to_i == post.user_id %>
                        <p><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        <span class="glyphicon-class"><%= link_to "(delete)", post_url(post.id), :method => 'delete' %></h5>
                        </span></p>
					<% end %>

			    </div>
			</div> 
		</div>
		<div class="col-md-4"></div>
	</div>
  <% end %>
  </div>

</ul>

app/views/posts/new.html.erb
<br></br>
<%= tinymce_assets %>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <%= form_tag "/posts" do %>

      <p>
      <label>Title:</label> <input name="title" size=30>
      </p>

        <%= text_area_tag :body, "", :class => "tinymce", :rows => 45, :cols => 50 %>
        <%= tinymce %>

      <button style="margin-top:10px; background-color:#218C8D" class="btn btn-small">Submit</button>
    <% end %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/posts/show.html.erb
<%= tinymce_assets %>

<div class="well">
	<div class="row">
		<div class="col-md-1">
			<% if session["user_id"].present? %>
				<p>
					<% if session["user_id"].to_i.equal?(@post.user_id) %>
						<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>					
						<span class="glyphicon-class"><%= link_to "Edit", edit_post_url(@post.id) %></span> 
					<% end %>
				</p>
			<% end %>
			<p>
				<span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
				<span class="glyphicon-class"><%= link_to "Back", posts_url %></span>
			</p>
		</div>

		<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><%= link_to @post.title, post_url(@post.id),  :method => 'get' %></h3>
                    <h6><%= link_to User.find_by(:id => @post.user_id).user_name, user_url(@post.user_id) %></h6>
                    <h6><%= @post.date %></h6>
					<% if session["user_id"].to_i.equal?(@post.user_id) %>
                      <p><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        <span class="glyphicon-class"><%= link_to "(delete)", post_url(@post.id), :method => 'delete' %></h5>
                      </span></p>
					<% end %>
				</div>
				<div class="panel-body"><%= simple_format(@post.body) %></div>
			</div>
          
            <ul>
                <label>Categories:</label><% @post.categories.pluck(:category_name).each do |category| %>
                    <%= category %>
                <% end %>
            </ul>

            <% if session["user_id"].to_i.equal?(@post.user_id) %>
                <ul>
                  <%= form_tag "/mappings", :method => 'post' do %>
                      <% Category.all.each do |category| %>
                      <%= check_box_tag 'category_ids[]', category.id %><%= category.category_name %>
                      <input type="hidden" name="post_id" value="<%= @post.id %>">
                  <% end %>
                  <button class="btn btn-small">Add Categories</button>
                  <% end %>
             </ul>
          <% end %>
		</div>
		<div class="col-md-1"></div>
	</div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10">
        <h4 style="clear:both; margin-top: 20px">Comments</h4>
        <%= form_tag "/comments", :method => 'post' do %>
            <%= text_area_tag :body, "", :class => "tinymce", :rows => 10, :cols => 50 %>
            <%= tinymce %>
            <input type="hidden" name="user_id" value="<%= @user_id %>">
            <input type="hidden" name="post_id" value="<%= @post.id %>">
            <p style="margin-top:10px"><button class="btn btn-small">Submit</button></p>
          <% end %>
      </div>
      <div class="col-md-1"></div>
    </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <ul class="list-group">
        <% @comments = Comment.where(post_id: @post.id).limit(100).order('date desc').page(params[:page]).per(5) %>
        <%= paginate @comments %>
         <% @comments.where(post_id: @post.id).order('date').each do |comment| %>
            <li href="#" class="list-group-item">
              <h4 style="font-family:verdana" class="list-group-item-heading"><%= link_to User.where(:id=>comment.user_id).pluck("user_name")[0],
                                                                                          user_url(comment.user_id)%></h4>
              <h6 style="font-family:verdana" class="list-group-item-heading"><%= comment.date %></h6>
              <p style="font-family:verdana" class="list-group-item-text"><%= simple_format(comment.body) %></p>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

app/views/relations/show.html.erb
<div class="well">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <%= link_to "Back to " + @user.user_name + "'s Profile", user_url(@user.id), :method=>'get' %>
        <h4>
            <%= @user.user_name + "'s " + @title %>
        </h4>
        <ul>
          <% @user_relations = @users.limit(1000).page(params[:page]).per(10) %>
          <%= paginate @user_relations %>
          <% @user_relations.each do |u| %>
              <li>
                <%=link_to u.user_name, user_url(u.id), :method=>'get' %>
              </li>
          <% end %>
        </ul>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul class="errors">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="well">
  <div class="row">
    <div class="col-xs-6 col-md-4"></div>
    <div class="col-xs-6 col-md-4">
      <h3>&nbsp;Sign Up</h3>
      <%= form_tag "/users" do %>
          <p style="margin-top:20px">
            <%= label_tag :* %>
            <%= text_field_tag :name, nil, :placeholder => 'User Name', :size => 25 %>
          </p>

          <p>
            <%= label_tag :* %>
            <%= text_field_tag :email, nil, :placeholder => 'Email Address', :size => 25 %>
          </p>

          <p>
            &nbsp;
            <%= text_field_tag :photo_url, nil, :placeholder => 'Photo URL', :size => 25 %>
          </p>

          <p>
            <%= label_tag :* %>
            <%= password_field_tag :password, nil, :placeholder => 'Password', :size => 25 %>
          </p>
           &nbsp;
          <%= submit_tag "Sign Me Up!", :class => "btn btn-large"%>
      <% end %>
    <div class="col-xs-6 col-md-4"></div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="well">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
      <% if @user.photo_url.blank? %>
          <p>
            <%= image_tag "http://www.mrwallpaper.com/wallpapers/cute-cat-head-1280x960.jpg",
            size: '150x150', :class => "img-circle"%>
          </p>
      <% else %>
        <p>
            <%= image_tag @user.photo_url, size: '150x150', :class => "img-circle"%>
        </p>
      <% end %>

      <p>
        <strong>Name:</strong> <%= @user.user_name %>
      </p>

      <p>
        <strong>Bio:</strong> <%= @user.intro %>
      </p>

      <p>
        <label>Following: </label>
        <%= link_to @user.followings.count,following_user_url(:id => @user.id), :method => 'get' %>
        <label>Followers: </label>
        <%= link_to @user.followers.count, followers_user_url(:id => @user.id), :method => 'get' %>
      </p>

      <% if session["user_id"].to_i.equal?(@user.id) %>
          <p>
            <strong>Email address on file:</strong> <%= @user.email %>
          </p>
      <% else %>
          <% @current_user = User.find_by(:id => session["user_id"]) %>
          <% if @current_user.following?(@user) %>
              <%= form_for(@current_user.active_relations.find_by(followed_id: @user.id),
                           html: { method: :delete }) do |f| %>
                  <%= f.submit "Unfollow", class: "btn btn-small" %>
              <% end %>
          <% else %>
              <%= form_for(@current_user.active_relations.build) do |f| %>
                  <div><%= hidden_field_tag :followed_id, @user.id %></div>
                  <%= f.submit "Follow", class: "btn btn-large" %>
              <% end %>
           <% end %>
      <% end %>

    </div>
    <div class="col-md-3">
      <p>
        <label>Posts: </label>
        <%= @user.posts.count %>
      </p>

      <ul>
        <% @my_posts = @user.posts.limit(100).order('date desc').page(params[:page]).per(10) %>
        <%= paginate @my_posts %>
        <% @my_posts.each do |post| %>
            <li><%= link_to post.title,post_url(post.id), :method => 'get' %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>