config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  ##### Sign Up and Sign In and Sign Out
  get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  # get '/users/:id' => 'users#show', as: :user

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  
  get "/signout" => 'sessions#destroy'
    
  resources :posts
  resources :comments
  resources :categories
  resources :mappings
  resources :users do
    member do
      get '/following' => 'users#following'
      get '/followers' => 'users#followers'
      get '/posts' => 'posts#index'
      get '/posts/friends' => 'posts#index'
    end
  end
  resources :relations
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :mappings, :dependent => :destroy
	has_many :posts, :through=> :mappings

	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :user
	
	validates :user_id, :presence => true
	validates :body, :presence => true, :allow_nil => false
	
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
	
	belongs_to :post
	belongs_to :category
	
	validates :category_id, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	has_many :mappings
	has_many :categories, :through => :mappings

	belongs_to :user
	
	validates :title, :presence => true, :allow_nil => false
	validates :user_id, :presence => true, :allow_nil => false
	
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :active_relations, :class_name => "Relation",
                              :foreign_key=> "follower_id",
                              :dependent => :destroy
  has_many :passive_relations, :class_name => "Relation",
           :foreign_key=> "followed_id",
           :dependent => :destroy

  has_many :followings, :through  => :active_relations, :source => :followed
  has_many :followers, :through  => :passive_relations, :source => :follower

  has_secure_password
  
  validates :email, :uniqueness => true, :allow_nil => false
  validates :user_name, :uniqueness => true, :allow_nil => false
  validates :password, :presence => true, :allow_nil => false

  # Follows a user.
  def follow(other_user)
    active_relations.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relations.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user
  def following?(other_user)
    followings.include?(other_user)
  end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
    c = Comment.new
    c.user_id = params["user_id"]
    c.post_id = params["post_id"]
    c.date = Time.now
    c.body = params["body"]
    c.save
    redirect_to "/posts/#{c.post_id}"   
end

end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController

def create
	array = params["category_ids"]

	if array.nil?
		redirect_to "/posts/#{params["post_id"]}"
	else
		array.each{|category_id|
		m = Mapping.new
			m.category_id = category_id
			m.post_id = params["post_id"]
			m.save
		}
		redirect_to "/posts/#{params["post_id"]}"
	end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 before_action :find_post, :only => [:show, :edit, :update, :destroy]
 before_action :require_user, :only => [:new, :edit, :update, :edit, :destroy]

 def find_post
 	@post = Post.find_by(id: params[:id])
 end

 def index
   # search bar
   if params["keyword"].present?
     @posts = Post.where("body LIKE ? or title LIKE ?", "%#{params[:keyword]}%","%#{params[:keyword]}%")
                  .limit(1000).order('date desc').page(params[:page]).per(5)

   else
     if params[:id].present?
       @user = User.find_by(id: session[:user_id])
       @url_path = request.original_url.to_s;

       # show friends' posts
       if @url_path.include?"friends"
         @page_id = "friends_posts"
         @users = @user.followings
         @posts = Post.where(:user_id => @users.pluck("id")).order('date desc').page(params[:page]).per(5)
       else
       # only show the signed in user's posts
         @page_id = "posts"
         @posts = @user.posts.order('date desc').page(params[:page]).per(5)
       end
       # home page shows all users' posts
     else
       @posts = Post.all.limit(1000).order('date desc').page(params[:page]).per(5)
     end
   end
 end

 def show
 	session["post_id"] = @post.id
 	@user_id = session["user_id"] 
	if @post == nil
		redirect to posts_url
    end
 end

 def require_user
	if session[:user_id].blank?
 		redirect_to root_url, notice: "You need to sign in first"
 	end
 end
	
 def new	
 	@post = Post.new
 	@user_id = session["user_id"]
 end

 def create
 	@post = Post.new
	@post.user_id = session["user_id"]
	@post.title = params[:title]
	@post.date = Time.now
	@post.body = params[:body]
	
	if @post.save
		redirect_to post_url(@post.id)
	else 
		render 'new'
  end

 end
 			
 def edit
 end

 def update

	@post.user_id = session["user_id"]
	@post.title = params[:title]
	@post.date = params[:date]
	@post.body = params[:body]
	@post.save
	
	redirect_to post_url(@post.id)
 end

 def destroy
    @post.delete
    redirect_to posts_url
 end

 def get_friends
   @page_id = "friends_posts"
   @user = User.find_by(id: params[:id])
   @users = @user.followings
   @posts = Post.where(:user_id => @users.pluck("id")).order('date desc').page(params[:page]).per(5)
   render posts_url

 end
 
end
	
	

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show]
  before_action :find_user, except: [:create, :authorize]

  def find_user
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_name: params[:name], email: params[:email], password: params[:password])
    if @user.save
      redirect_to root_url, notice: "Thanks for signing up."
    else
      render "new"
    end

  end
  
  def authorize

   if session[:user_id].blank? 
   		redirect_to root_url, notice: "Nice try!"
   end

  end
  
  def show
    @page_id = "profile"
  end

  def following

    @title = "Following"
    @users = @user.followings
    render 'relations/show.html'

  end

  def followers

    @title = "Followers"
    @users = @user.followers
    render 'relations/show.html'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <style>
  body {
	  padding-top: 45px;
  }
  </style>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if notice.present? %>
      <div class="alert alert-info"%>
        <%= notice %>
      </div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top">
		<div class="navbar-collapse collapse">

	    <% if session["user_id"].present? %>
		    <a class="navbar-brand" href="/">
		        <%= image_tag("cat.png", :alt => "Brand")%>
            </a>

            <ul class ="nav navbar-nav <%= @page_id == "posts" ? "active" : "" %>">
				<%= link_to ("WELCOME, " + User.find_by(id: session["user_id"]).user_name), posts_user_url(id: session["user_id"]),:class=>"navbar-brand changeFontBig"%>
            </ul>

            <% if @user.nil? or session["user_id"].to_i.equal?(@user.id)  %>
                <ul class ="nav navbar-nav <%= @page_id == "profile" ? "active" : "" %>">
                    <%= link_to "MY PROFILE", user_url(User.find_by(id: session["user_id"])), :class=>"navbar-brand changeFont" %>
                </ul>
            <% else %>
                <ul class ="nav navbar-nav">
                    <%= link_to "MY PROFILE", user_url(User.find_by(id: session["user_id"])), :class=>"navbar-brand changeFont" %>
                </ul>
            <% end %>

            <ul class ="nav navbar-nav <%= @page_id == "friends_posts" ? "active" : "" %>">
              <%= link_to "FRIENDS' MEOWS", posts_friends_user_url(id: session["user_id"]), :class=>"navbar-brand changeFont" %>
            </ul>

            <ul class="nav navbar-nav changeFont">
                <%= link_to "Sign Out", '/signout', :class => "navbar-brand changeFont"%>
            </ul>

            <ul class="nav navbar-nav"></ul>
                <%= form_tag posts_url, :method => "get", :class => "navbar-form navbar-right" do %>
                  <div class="form-group">
                    <%= text_field_tag :keyword %>
                  </div>
                   <%= submit_tag "Search", :class =>"btn btn-default" %>
                <% end %>
            </ul>

	    <% else %>
		    <a class="navbar-brand">
		        <%= image_tag("cat.png", :alt => "Brand")%>
				<%= link_to "MEOW Blog", '/', :class => "navbar-brand changeFontBig" %>
		    </a>

            <ul class ="nav navbar-nav changeFont">
				<%= link_to "Sign Up", '/signup', :class => "navbar-brand changeFont"%>
             </ul>

            <ul class ="nav navbar-nav changeFont">
				<%= link_to link_to "Sign In", '/login', :class => "navbar-brand changeFont"%>
			</ul>
          <% end %>
    </div>
	</nav>
<%= yield %>
</body>
</html>